export const GET_DATA = "GET_DATA";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const GET_SERIES = "GET_SERIES";
export const GET_SERIES_LISTING = "GET_SERIES_LISTING";
export const SET_CURRENT_SERIES = "SET_CURRENT_SERIES";
export const GET_MATCH_LIST = "GET_MATCH_LIST";
